flowchart TD
    A["@A@"] --> B["@for@ B@"] & C@{ label: "@for@ c@"} & E{"`@for@ E@`"} & D(("@for@ D@"))
      H1{{"@for@ H@"}}
      H2{{"`@for@ H@`"}}
      Q1{"@for@ Q@"}
      Q2{"`@for@ Q@`"}
      AS1>"@for@ AS@"]
      AS2>"`@for@ AS@`"]
