gitGraph
   commit id: "init"
   commit id: "second"
   branch develop
   checkout develop
   commit id: "dev1"
   commit id: "dev2"
   checkout main
   merge develop id: "m1" tag: "v1.0"
   commit id: "after"
