gitGraph
   commit id: "root"
   branch b1
   commit id: "c1"
   checkout main
   branch b2
   commit id: "c2"
   checkout main
   branch b3
   commit id: "c3"
   checkout main
   merge b1
   merge b2
   merge b3 tag: "all"
