architecture-beta
      group __proto__(cloud)[P]
      group myPrototypePollutionKey(cloud)[Real]
      service a(server)[A] in __proto__
      service b(server)[B] in myPrototypePollutionKey
      a:R -- L:b
