gitGraph:
          commit
          branch testBranch
          checkout testBranch
          commit
          checkout main
          %% Merge Tag and ID
          merge testBranch tag: "merge-tag" id: "2-222"
          branch testBranch2
          checkout testBranch2
          commit
          checkout main
          %% Merge ID and Tag (reverse order)
          merge testBranch2 id: "4-444" tag: "merge-tag2" type:HIGHLIGHT
          branch testBranch3
          checkout testBranch3
          commit
          checkout main
          %% just Merge ID
          merge testBranch3 id: "6-666"
