gitGraph
     commit id:"initial commit"
     commit id:"work on first release"
     commit id:"design freeze from here"
     branch v1-rc
     checkout v1-rc
     commit id:"bugfix 1"
     commit id:"bigfix 2" tag:"v1.0.1"
     branch FORK-v1.0-MDR
     checkout FORK-v1.0-MDR
     commit id:"working on MDR"
     checkout v1-rc
     commit id:"minor design changes for MDR" tag:"v1.0.2"
     checkout FORK-v1.0-MDR
     merge v1-rc
     checkout main
     commit id:"new feature for v1.1…"
     checkout FORK-v1.0-MDR
     commit id:"working on MDR"
     commit id:"finishing MDR"
     branch v1.0-MDR
     checkout v1.0-MDR
     commit id:"brush up release" tag:"v1.0.2-MDR"
     checkout v1-rc
     commit id:"bugfix without MDR"
     checkout main
     commit id:"work on v1.1"
