sequenceDiagram
actor Bob
actor Alice
    Bob -|\ Alice: Hello Alice, how are you?
    Bob -|/ Alice: Hello Alice, how are you?
    Bob -// Alice: Hello Alice, how are you?
    Bob -\\ Alice: Hello Alice, how are you?

    Bob \|- Alice: Hello Alice, how are you?
    Bob /|- Alice: Hello Alice, how are you?
    Bob //- Alice: Hello Alice, how are you?
    Bob \\- Alice: Hello Alice, how are you?        
