sequenceDiagram
    participant Alice@{ "type" : "database" }
    participant Bob@{ "type" : "database" }
    participant Carl@{ type: "database" }
    participant David@{ "type" : 'database' }
    participant Eve@{ type: 'database' }
    participant Favela@{ "type" : "database"    }
    Bob->>+Alice: Hi Alice
    Alice->>+Bob: Hi Bob
