   xychart horizontal
   title "Basic xychart"
   x-axis "this is x axis" [category1, "category 2", category3]
   y-axis yaxisText 10 --> 150
bar barTitle1 [23, 45, 56.6]
line lineTitle1 [11, 45.5, 67, 23]
bar barTitle2 [13, 42, 56.89]
   line lineTitle2 [45, 99, 012]
