gantt
dateFormat YYYY-MM-DD
title Adding gantt diagram functionality to mermaid
section Documentation
task A: a, 2024-01-27, 2024-01-28
task B: b, after a, 2024-01-30
task C: c, 2024-01-20, until a
task D: d, after c, until b
