erDiagram
              CUSTOMER ||--o{ 1 : places
              1 ||--|{ u : contains
              u {
                string name
                int quantity
              }
              "2.5" ||--|| ORDER : processes
              ORDER {
                int id
                date created
              }
