#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
#
# Generate the flowchart shape-name table from a mermaid checkout.
#
#   scripts/gen-flowchart-shapes.py --checkout ~/src/mermaid \
#       > src/fymm-flowchart-shapes.inc
#
# `@{ shape: <name> }` takes a shape's short name or one of its public
# aliases. An internal alias is not accepted from a source, and an unknown
# name is an error, so both have to be told apart from a valid name.
#
# The table is committed; the build never runs this script.

import argparse
import re
import sys

REGISTRY = ('packages/mermaid/src/rendering-util/rendering-elements/shapes.ts')


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--checkout', required=True)
    args = ap.parse_args()

    text = open('%s/%s' % (args.checkout, REGISTRY)).read()

    names, internal = set(), set()
    for m in re.finditer(r'shortName:\s*[\'"]([^\'"]+)[\'"]', text):
        names.add(m.group(1))
    for m in re.finditer(r'\baliases:\s*\[([^\]]*)\]', text):
        names.update(re.findall(r'[\'"]([^\'"]+)[\'"]', m.group(1)))
    for m in re.finditer(r'\binternalAliases:\s*\[([^\]]*)\]', text):
        internal.update(re.findall(r'[\'"]([^\'"]+)[\'"]', m.group(1)))

    names -= internal
    if not names:
        sys.exit('no shapes found in %s' % REGISTRY)

    print('/* Generated by scripts/gen-flowchart-shapes.py. */')
    print('static const char *const fymm_flowchart_shapes[] = {')
    for n in sorted(names):
        print('\t"%s",' % n)
    print('};')
    print('/* accepted by the renderer but not from a source */')
    print('static const char *const fymm_flowchart_internal_shapes[] = {')
    for n in sorted(internal):
        print('\t"%s",' % n)
    print('};')


if __name__ == '__main__':
    main()
